export const path = {
  home: "/doctor/login-view",
  signUp: "/doctor/join-view",
  selfDiagnosis: "/selfDiagnosis",
  appointment: "/appointment/:id",
  map: "/map",
  pay: "/pay",
  mypage: "/mypage",
  chat: "/chat",
  hospitalPage: "/hospitalPage",
  adminAppointment: "/adminAppointment",
  adminWaitingList: "/doctor/waiting-list-view",
  accounting: "/accounting",
  teleConsult: "/teleConsult",
  billing: "/billing",
  search: "/searchHospital",
  medicalcaremanagement: "/medicalcaremanagement/:id",
};
