export const path = {
  home: "/",
  signUp: "/signUp",
  selfDiagnosis: "/selfDiagnosis",
  appointment: "/appointment/:id",
  map: "/map",
  pay: "/pay",
  mypage: "/mypage",
  chat: "/chat",
  hospitalPage: "/hospitalPage",
  adminAppointment: "/adminAppointment",
  adminWaitingList: "/adminWaitingList",
  accounting: "/accounting",
  teleConsult: "/teleConsult",
  billing: "/billing",
  search: "/searchHospital",
};
